spring:
  datasource:
    url: jdbc:h2:mem:credit_system
    username: sa
    password: sa
  jpa:
    show-sql: true
  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        trace: false
        web-allow-others: false
